export const CATEGORIES = [
  "League",
  "Season Records",
  "Matchup",
  "Draft & Transactions",
  "Roster",
  "Stats",
  "Streaks & Droughts",
  "Milestones",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const RECORD_CATEGORY: Record<string, Category> = {
  // ── League ──────────────────────────────────────────────────────────────
  total_wins: "League",
  total_losses: "League",
  win_pct: "League",
  total_points: "League",
  total_opp_points: "League",
  career_ppg: "League",
  championships: "League",
  runner_up_finishes: "League",
  third_place_finishes: "League",
  total_medals: "League",
  medal_score: "League",
  playoff_appearances: "League",
  playoff_wins: "League",
  playoff_losses: "League",
  playoff_points: "League",
  playoff_opp_points: "League",
  total_playoff_pts: "League",
  most_playoff_ppg: "League",
  reg_season_titles: "League",
  reg_season_wins: "League",
  season_ap_titles: "League",
  season_pts_titles: "League",
  most_finals_appearances: "League",
  most_semifinal_appearances: "League",
  most_quarterfinal_wins: "League",
  most_semifinal_wins: "League",
  seasons_played: "League",
  consol_wins: "League",
  toiletbowl_finishes: "League",
  best_playoff_win_pct: "League",
  worst_playoff_win_pct: "League",
  fewest_playoff_appearances: "League",
  winning_record_seasons: "League",
  losing_record_seasons: "League",
  top_seed_losses_total: "League",
  top_seed_losses_semifinal: "League",
  top_seed_losses_final: "League",
  underdog_wins_semifinal: "League",
  underdog_wins_final: "League",
  most_underdog_wins: "League",
  most_playoff_appearances_no_title: "League",

  // ── Season Records ───────────────────────────────────────────────────────
  most_season_wins: "Season Records",
  most_season_losses: "Season Records",
  most_season_points: "Season Records",
  fewest_season_points: "Season Records",
  season_score_best: "Season Records",
  season_score_worst: "Season Records",
  most_season_opp_pts: "Season Records",
  fewest_season_opp_pts: "Season Records",
  most_season_high_scores: "Season Records",
  most_season_top_scores: "Season Records",
  most_season_bottom_scores: "Season Records",
  most_season_worst_scores: "Season Records",
  most_season_top_half: "Season Records",
  most_season_bottom_half: "Season Records",
  most_season_ap_wins: "Season Records",
  most_season_ap_losses: "Season Records",
  best_season_ap_pct: "Season Records",
  most_season_blowout_wins: "Season Records",
  most_season_blowout_losses: "Season Records",
  most_season_narrow_wins: "Season Records",
  most_season_narrow_losses: "Season Records",
  most_weeks_first_place_season: "Season Records",
  best_ppg: "Season Records",
  worst_ppg: "Season Records",
  highest_season_pts_share: "Season Records",
  lowest_season_pts_share: "Season Records",
  highest_season_opp_pts_share: "Season Records",
  lowest_season_opp_pts_share: "Season Records",
  hardest_season_sos: "Season Records",
  easiest_season_sos: "Season Records",
  most_different_players_season: "Season Records",
  most_perfect_lineups_season: "Season Records",
  most_points_single_player_season: "Season Records",
  highest_pct_single_player_season: "Season Records",
  most_expected_wins_season: "Season Records",
  most_unlucky_season: "Season Records",
  most_consistent_season: "Season Records",
  least_consistent_season: "Season Records",
  most_weeks_above_median_season: "Season Records",
  most_weeks_below_median_season: "Season Records",
  best_season_luck: "Season Records",
  worst_season_luck: "Season Records",

  // ── Matchup ──────────────────────────────────────────────────────────────
  most_matchup_points: "Matchup",
  fewest_matchup_points: "Matchup",
  biggest_blowout: "Matchup",
  narrowest_win: "Matchup",
  largest_margin_victory: "Matchup",
  smallest_margin_victory: "Matchup",
  largest_margin_defeat: "Matchup",
  smallest_margin_defeat: "Matchup",
  highest_combined_score: "Matchup",
  lowest_combined_score: "Matchup",
  highest_points_share: "Matchup",
  lowest_points_share: "Matchup",
  most_points_in_loss: "Matchup",
  fewest_points_in_win: "Matchup",
  most_playoff_matchup_pts: "Matchup",
  fewest_playoff_matchup_pts: "Matchup",
  biggest_playoff_blowout: "Matchup",
  narrowest_playoff_win: "Matchup",
  highest_playoff_combined: "Matchup",
  lowest_playoff_combined: "Matchup",
  high_scores: "Matchup",
  top_scores: "Matchup",
  worst_scores: "Matchup",
  bottom_scores: "Matchup",
  high_score_pct: "Matchup",
  top_score_pct: "Matchup",
  bottom_score_pct: "Matchup",
  worst_score_pct: "Matchup",
  blowout_wins: "Matchup",
  blowout_losses: "Matchup",
  narrow_wins: "Matchup",
  narrow_losses: "Matchup",
  top_half: "Matchup",
  bottom_half: "Matchup",
  top_half_pct: "Matchup",
  bottom_half_pct: "Matchup",
  allplay_wins: "Matchup",
  allplay_losses: "Matchup",
  allplay_win_pct: "Matchup",
  points_share_avg: "Matchup",
  opp_points_share_avg: "Matchup",
  most_games_vs_top_scorer: "Matchup",
  most_games_vs_bottom_scorer: "Matchup",
  most_games_vs_top_half: "Matchup",
  most_h2h_wins: "Matchup",
  most_h2h_losses: "Matchup",
  fewest_h2h_wins: "Matchup",
  fewest_h2h_losses: "Matchup",
  most_h2h_points: "Matchup",
  fewest_h2h_points: "Matchup",
  easiest_sos: "Matchup",
  hardest_sos: "Matchup",

  // ── Draft & Transactions ─────────────────────────────────────────────────
  best_draft_pick_ever: "Draft & Transactions",
  worst_draft_pick_ever: "Draft & Transactions",
  best_draft_season: "Draft & Transactions",
  worst_draft_season: "Draft & Transactions",
  best_qb_draft_pick: "Draft & Transactions",
  worst_qb_draft_pick: "Draft & Transactions",
  best_qb_draft_season: "Draft & Transactions",
  worst_qb_draft_season: "Draft & Transactions",
  best_rb_draft_pick: "Draft & Transactions",
  worst_rb_draft_pick: "Draft & Transactions",
  best_rb_draft_season: "Draft & Transactions",
  worst_rb_draft_season: "Draft & Transactions",
  best_wr_draft_pick: "Draft & Transactions",
  worst_wr_draft_pick: "Draft & Transactions",
  best_wr_draft_season: "Draft & Transactions",
  worst_wr_draft_season: "Draft & Transactions",
  best_te_draft_pick: "Draft & Transactions",
  worst_te_draft_pick: "Draft & Transactions",
  best_te_draft_season: "Draft & Transactions",
  worst_te_draft_season: "Draft & Transactions",
  best_k_draft_pick: "Draft & Transactions",
  worst_k_draft_pick: "Draft & Transactions",
  best_k_draft_season: "Draft & Transactions",
  worst_k_draft_season: "Draft & Transactions",
  best_dst_draft_pick: "Draft & Transactions",
  worst_dst_draft_pick: "Draft & Transactions",
  best_dst_draft_season: "Draft & Transactions",
  worst_dst_draft_season: "Draft & Transactions",
  overall_draft_value: "Draft & Transactions",
  qb_draft_value: "Draft & Transactions",
  rb_draft_value: "Draft & Transactions",
  wr_draft_value: "Draft & Transactions",
  te_draft_value: "Draft & Transactions",
  k_draft_value: "Draft & Transactions",
  dst_draft_value: "Draft & Transactions",
  most_first_overall_picks: "Draft & Transactions",
  most_first_round_rbs: "Draft & Transactions",
  most_first_round_wrs: "Draft & Transactions",
  most_first_round_qbs: "Draft & Transactions",
  most_first_round_tes: "Draft & Transactions",
  highest_avg_draft_pos: "Draft & Transactions",
  lowest_avg_draft_pos: "Draft & Transactions",
  most_trades: "Draft & Transactions",
  best_trade_value: "Draft & Transactions",
  worst_trade_value: "Draft & Transactions",
  best_trade_season_value: "Draft & Transactions",
  worst_trade_season_value: "Draft & Transactions",
  best_trade_season_count: "Draft & Transactions",
  most_transactions: "Draft & Transactions",
  best_waiver_pickup: "Draft & Transactions",
  best_waiver_season: "Draft & Transactions",
  worst_waiver_season: "Draft & Transactions",
  top_waiver_value: "Draft & Transactions",
  worst_waivers: "Draft & Transactions",
  best_moves_season: "Draft & Transactions",
  overall_manager_value: "Draft & Transactions",
  best_manager_season: "Draft & Transactions",
  worst_manager_season: "Draft & Transactions",

  // ── Roster ───────────────────────────────────────────────────────────────
  most_qb_all_points: "Roster",
  most_qb_season_points: "Roster",
  most_qb_week_points: "Roster",
  most_rb_all_points: "Roster",
  most_rb_season_points: "Roster",
  most_rb_week_points: "Roster",
  most_wr_all_points: "Roster",
  most_wr_season_points: "Roster",
  most_wr_week_points: "Roster",
  most_te_all_points: "Roster",
  most_te_season_points: "Roster",
  most_te_week_points: "Roster",
  most_k_all_points: "Roster",
  most_k_season_points: "Roster",
  most_k_week_points: "Roster",
  most_dst_all_points: "Roster",
  most_dst_season_points: "Roster",
  most_dst_week_points: "Roster",
  qb_avg_pts_all: "Roster",
  qb_avg_pts_worst: "Roster",
  qb_avg_pts_season: "Roster",
  qb_avg_pts_season_worst: "Roster",
  rb_avg_pts_all: "Roster",
  rb_avg_pts_worst: "Roster",
  rb_avg_pts_season: "Roster",
  rb_avg_pts_season_worst: "Roster",
  wr_avg_pts_all: "Roster",
  wr_avg_pts_worst: "Roster",
  wr_avg_pts_season: "Roster",
  wr_avg_pts_season_worst: "Roster",
  te_avg_pts_all: "Roster",
  te_avg_pts_worst: "Roster",
  te_avg_pts_season: "Roster",
  te_avg_pts_season_worst: "Roster",
  k_avg_pts_all: "Roster",
  k_avg_pts_worst: "Roster",
  k_avg_pts_season: "Roster",
  k_avg_pts_season_worst: "Roster",
  dst_avg_pts_all: "Roster",
  dst_avg_pts_worst: "Roster",
  dst_avg_pts_season: "Roster",
  dst_avg_pts_season_worst: "Roster",
  most_bench_all_points: "Roster",
  most_bench_season_points: "Roster",
  most_bench_week_points: "Roster",
  fewest_bench_all_points: "Roster",
  fewest_bench_points_season: "Roster",
  fewest_bench_week_points: "Roster",
  most_bench_pts_in_loss: "Roster",
  most_bench_pts_in_win: "Roster",
  coach_score_alltime: "Roster",
  coach_score_worst_alltime: "Roster",
  coach_score_season_best: "Roster",
  coach_score_season_worst: "Roster",
  coach_score_perfect_games: "Roster",
  coach_score_perfect_season: "Roster",
  coach_score_perfect_streak: "Roster",
  coach_score_perfect_drought: "Roster",
  optimal_pts_missed_all: "Roster",
  optimal_pts_missed_season: "Roster",
  most_weekly_leaders_qb_all: "Roster",
  most_weekly_leaders_qb_season: "Roster",
  most_weekly_leaders_rb_all: "Roster",
  most_weekly_leaders_rb_season: "Roster",
  most_weekly_leaders_wr_all: "Roster",
  most_weekly_leaders_wr_season: "Roster",
  most_weekly_leaders_te_all: "Roster",
  most_weekly_leaders_te_season: "Roster",
  most_weekly_leaders_k_all: "Roster",
  most_weekly_leaders_k_season: "Roster",
  most_weekly_leaders_dst_all: "Roster",
  most_weekly_leaders_dst_season: "Roster",
  most_weekly_leaders_flex_all: "Roster",
  most_weekly_leaders_flex_season: "Roster",
  top_player_season: "Roster",
  top_player_week: "Roster",
  most_points_single_player_career: "Roster",

  // ── Stats ────────────────────────────────────────────────────────────────
  most_consistent_team: "Stats",
  least_consistent_team: "Stats",
  highest_median_score: "Stats",
  lowest_median_score: "Stats",
  most_weeks_above_avg: "Stats",
  most_weeks_below_avg: "Stats",
  most_weeks_top_scorer: "Stats",
  most_weeks_second_scorer: "Stats",
  most_weeks_top3: "Stats",
  most_weeks_top_quarter: "Stats",
  most_weeks_first_place: "Stats",
  most_weeks_last_place: "Stats",
  most_expected_wins_all: "Stats",
  most_wins_below_avg: "Stats",
  most_losses_above_avg: "Stats",
  luckiest: "Stats",
  unluckiest: "Stats",
  largest_week_swing: "Stats",
  most_150plus_games: "Stats",
  most_200plus_games: "Stats",
  most_sub80_games: "Stats",

  // ── Streaks & Droughts ───────────────────────────────────────────────────
  win_streak: "Streaks & Droughts",
  loss_streak: "Streaks & Droughts",
  win_start_streak: "Streaks & Droughts",
  loss_start_streak: "Streaks & Droughts",
  top_score_streak: "Streaks & Droughts",
  top_score_drought: "Streaks & Droughts",
  high_score_streak: "Streaks & Droughts",
  high_score_drought: "Streaks & Droughts",
  top_half_streak: "Streaks & Droughts",
  top_half_drought: "Streaks & Droughts",
  playoff_appearance_streak: "Streaks & Droughts",
  playoff_appearance_drought: "Streaks & Droughts",
  championship_streak: "Streaks & Droughts",
  championship_drought: "Streaks & Droughts",
  winning_record_streak: "Streaks & Droughts",
  winning_record_drought: "Streaks & Droughts",
  title_game_streak: "Streaks & Droughts",
  title_game_drought: "Streaks & Droughts",
  medal_streak: "Streaks & Droughts",
  medal_drought: "Streaks & Droughts",

  // ── Milestones ───────────────────────────────────────────────────────────
  wire_to_wire_champion: "Milestones",
  lowest_seed_champion: "Milestones",
  worst_champion_record: "Milestones",
};
